#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'pubsub_worker'
require 'optparse/kwargs'

opts = {
  require: './config/environment',
  topics: ['default'],
  suffix: 'worker'
}

parser = OptionParser.new

parser.on '--[no-]require=PATH' do |v|
  opts[:require] = v
end


parser.on '--topics=topic1,topic2..' do |v|
  opts[:topics] = v.split(',')
end

parser.on '--subscription-suffix=suffix' do |v|
  opts[:suffix] = v
end

parser.parse ARGV

require opts[:require] if opts[:require]

pubsub = Google::Cloud::Pubsub.new

begin
  PubsubWorker::Base.new(pubsub: pubsub, topics: opts[:topics], subscription_suffix: opts[:suffix]).run
rescue Interrupt
  exit
end
